### ISSUE TITLE
Support inline code comments

### ISSUE THREAD

**Issue by teeberg** [severest/giphub#9]
Where's the GIF button? 😱 

![image](https://user-images.githubusercontent.com/199071/40377252-4b72caf8-5da5-11e8-9795-39e92da4caa2.png)

**Comment by severest** [comment]
yea, these textareas are different from the rest of them and I haven't got them to work properly yet :(

**Comment by teeberg** [comment]
I think this was addressed in https://github.com/severest/giphub/commit/5aca8c4aeb7b9fae3d585b8c656957735ea92c82
